### ISSUE TITLE
Reproduce canonical junctions

### ISSUE THREAD

**Issue by jacobljh** [ding-lab/misplice#2]
After running through MiSplice, I found the output columns only match sheet 1 of tableS1. However, the canonical junction position is on the sheet MaxEntScore. 

Could you kindly give a light on how to produce the canonical junction position?

**Comment by caosgc33d** [comment]
MiSplice pipeline does not automatically output canonical junction position.  You can extract the closest canonical junction position based on Ensembl DB.
