### ISSUE TITLE
bampath.txt

### ISSUE THREAD

**Issue by BGIHENG** [ding-lab/misplice#3]
hi, I want to use your pipeline, but I do not known how to prepare bampath.txt file. So could you tell me about bampath.txt file?

**Comment by reykajayasinghe** [comment]
Please refer to the example of what the bampath file looks like here:
https://github.com/ding-lab/misplice/blob/master/resource/bampath.txt

This is a tab delimited file that has the following data:
sample, cancer type, full location of bam, chr1 or 1 depending on if chromosomes have a "chr" or just the chromosome number indicated in the bam. 

TCGA-06-0649-01B-01R-1849-01 gbm /gscmnt/gc2741/ding/TCGA_RNA/GBM/TCGA-06-0649-01B-01R-1849-01.bam 1
TCGA-41-3915-01A-01R-1850-01 gbm /gscmnt/gc2741/ding/TCGA_RNA/GBM/TCGA-41-3915-01A-01R-1850-01.bam chr1
TCGA-06-0190-01A-01R-1849-01 gbm /gscmnt/gc2741/ding/TCGA_RNA/GBM/TCGA-06-0190-01A-01R-1849-01.bam 1
TCGA-28-5213-01A-01R-1850-01 gbm /gscmnt/gc2741/ding/TCGA_RNA/GBM/TCGA-28-5213-01A-01R-1850-01.bam chr1

Hope that helps!

**Comment by BGIHENG** [comment]
I have another question about "Bed file for step 2 and step 4 can be found from https://drive.google.com/file/d/14vHI3G45c-xBzpgzs_I43orrKbNJyIVi/view?usp=sharing"，I could not get these two bed files. Could you help me and tell me how to use these two bed files ?
