### ISSUE TITLE
bed files

### ISSUE THREAD

**Issue by BGIHENG** [ding-lab/misplice#5]
hi，
I have another question about "Bed file for step 2 and step 4 can be found from https://drive.google.com/file/d/14vHI3G45c-xBzpgzs_I43orrKbNJyIVi/view?usp=sharing"，I could not get these two bed files. Could you help me and tell me how to use these two bed files ?

Thanks~

**Comment by reykajayasinghe** [comment]
The link should work. You need to click the download button when you open the link.

https://drive.google.com/file/d/14vHI3G45c-xBzpgzs_I43orrKbNJyIVi/view
