### ISSUE TITLE
How to get variant peptide

### ISSUE THREAD

**Issue by BGIHENG** [ding-lab/misplice#6]
Hi,

I have finished SCM detection using Misplice.  Could you tell us how to get variant peptide (8-mer, 9-mer, 10-mer) according the result.

Thanks ~

**Comment by caosgc33d** [comment]
Generating different length of peptides is not a part of MiSplice pipeline. You can look other neoantigen detection pipeline such as INTEGRATE-neo, or pVACseq, etc.
